module.exports = {
    "db": "mongodb://localhost:27017/mybrand",
    // "db": "mongodb+srv://mybrand:globalpass@cluster0.8vbbk.mongodb.net/mybrand?retryWrites=true&w=majority",
    "logdb": "mongodb://localhost:27017/artinfo",
    "mongodbClient": "mongodb://localhost:27017/mybrand",
    "eshost": "localhost:9200",
    "eshost1": "localhost:9200",
    "SYNCQUEUE": "DataSyncQueue",
    // "env": "stage",
    "env": "dev",
    "esremotehost" : "http://localhost:9200/",
    //  "esremotehost": "https://search-bai-app-4out33ss2nv3atqi3xgadgaqc4.ap-south-1.es.amazonaws.com/",
   // "esremotehost": "https://vpc-blouinartinfo-aj26nejxoyy3artqde5gi74fvy.us-east-1.es.amazonaws.com",
    // "awsRegion": "us-east-1",
    "awsRegion": "ap-south-1",
    // "esAccessKey": "AKIAIDT2ISJ5VDTAYF7Q",
    "esSecretKey": "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",
    "esAccessKey": "AKIAIDT2ISJ5VDTAYF7Q",
   // "esSecretKey": "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",
    "httpPort": 3001,
    "httpsPort": 4001,
    "REDIS_HOST": "localhost",
    "REDIS_PORT": 6379,
    "SSLOn": false,
    "Cloud name": 'drxjinfid',
    // "API Key": 131926629964935,
    // "API Secret": "rZZNlNOj3DsJ1tAx8Nr9TefFy_g"
    //"API Key": "AKIAVSYFW7UGKZVSLMG6",
    //"API Secret": "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"
};